### ISSUE TITLE
[Linux 4.8.6] New perf script output format

### ISSUE THREAD

**Issue by jesperpedersen** [brendangregg/FlameGraph#112]
I have installed kernel 4.8.6, and doing
```
perf record -F 99 -a -g -- sleep 10
```
followed by
```
perf script
```
gives
```
swapper     0 [000]   147.374682:          1 cycles:ppp: 
        ffffffff810631d4 native_write_msr+0x4 ([kernel.kallsyms])
        ffffffff8100b720 intel_pmu_enable_all+0x10 ([kernel.kallsyms])
        ffffffff81007403 x86_pmu_enable+0x263 ([kernel.kallsyms])
        ffffffff8117dcc2 perf_pmu_enable+0x22 ([kernel.kallsyms])
        ffffffff8117eba1 ctx_resched+0x51 ([kernel.kallsyms])
        ffffffff8117ed90 __perf_event_enable+0x1e0 ([kernel.kallsyms])
        ffffffff81177726 event_function+0xa6 ([kernel.kallsyms])
        ffffffff81178c1f remote_function+0x3f ([kernel.kallsyms])
        ffffffff8110887b flush_smp_call_function_queue+0x7b ([kernel.kallsyms])
        ffffffff81109363 generic_smp_call_function_single_interrupt+0x13 ([kernel.kallsyms])
        ffffffff81050d87 smp_call_function_single_interrupt+0x27 ([kernel.kallsyms])
        ffffffff8173ceec call_function_single_interrupt+0x8c ([kernel.kallsyms])
        ffffffff815b3427 cpuidle_enter+0x17 ([kernel.kallsyms])
        ffffffff810c6f6b cpu_startup_entry+0x2cb ([kernel.kallsyms])
        ffffffff8172dd47 rest_init+0x77 ([kernel.kallsyms])
        ffffffff81da5191 start_kernel+0x4a7 ([kernel.kallsyms])
        ffffffff81da45d6 x86_64_start_reservations+0x2a ([kernel.kallsyms])
        ffffffff81da4724 x86_64_start_kernel+0x14c ([kernel.kallsyms])
```

F.ex. ```x86_64_start_kernel+0x14c``` instead of ```x86_64_start_kernel```.

Should ```stackcollapse-perf.pl``` automatically remove this, or should there be a new option for it ?

RHEL 7.2 w/ kernel-ml-4.8.6 from ELRepo.

**Comment by KungFuJesus** [comment]
I took have this issue, I've fixed it with a patch, though arguably I could be applying it in the wrong place (the original regex the match happens on could be written so that the +0xaddress doesn't get captured)

See my pull request:
https://github.com/brendangregg/FlameGraph/pull/114

**Comment by brendangregg** [comment]
ok, sorry, I need to catch up with the PRs.

**Comment by KungFuJesus** [comment]
It may make more sense to modify the regex to have an optional capture group (not sure if perl regexes support this or not).  Otherwise just adding it to the match expression means it will fail on older kernels.  Or you could just do what I did inside the if expression with another regex inside. 

Just full disclosure, I don't know a lick of perl, I figured out how to do what I did by googling things.

**Comment by chrishantha** [comment]
I also faced the same issue with perf script output in version 4.8.6. I'm using Ubuntu and the kernel version is 4.8.0-30-generic.

As a temporary workaround, I used sed to remove the hexadecimal part in the function.

`sudo perf script | sed -r 's/\+0x[a-f0-9]+//' > out.stacks`

**Comment by brendangregg** [comment]
Thanks, should be fixed now with my latest pushes. Importantly, it passes the bundled tests, which cover older kernels.
