### ISSUE TITLE
Non-default height parameter causes overlap with "Reset Zoom" and page title

### ISSUE THREAD

**Issue by bastianbeischer** [brendangregg/FlameGraph#125]
Hi,

when creating a flamegraph with --height=32 the SVG which is created does contain a flamegraph with larger rows, but the "Reset Zoom" button and the page title "Flame Graph" on top are now partially hidden underneath the flamegraph itself.

Thanks for the great tool and for looking into this issue.

**Comment by brendangregg** [comment]
Thanks, you're right, that was an off-by-one error that caused it. Fixed
