### ISSUE TITLE
Functions call trace is incorrect

### ISSUE THREAD

**Issue by zorrohahaha** [brendangregg/FlameGraph#182]
I am using the FlameGraph to check an interface performance issue. But I find that it is a little weird of the call trace.
I tested the latency with RDMA perftest, and now I take ib_write_lat as an example.
The "main" function entry will finally call "run_iter_lat_write" in a loop way as the main path. In the "run_iter_lat_write", the "mlx5_post_send" will be called as an callback function pointer. Then "mlx5_poll_cq_1" will be called with the path "ibv_poll_cq->function pointer->mlx5_poll_cq_1". And an loop waiting for the memory counter flag in the "run_iter_lat_write" will also take a long time.

In the functions with mlx5 prefix, some pthread_spinlock functions will be called.

After I tried two times, the svg showed a strange call trace. There is sth marked as "unknown". And mlx5_poll_cq_1 / pthread_spin_lock are at the same level. Then on top of "unknown", there is another "mlx5_poll_cq_1" and the "run_iter_lat_write".
From the code, "run_iter_lat_write" should contains all and the "pthread_spin_lock" should on top of post send and poll cq functions.

Do I miss something?

**perf record -F 4999 -C 13 -ag sleep 20
perf script | ./stackcollapse-perf.pl > out.perf-folded-13
./flamegraph.pl out.perf-folded-13 > perf-13.svg**

[perf-13.zip](https://github.com/brendangregg/FlameGraph/files/2381766/perf-13.zip)

**Comment by aprilweet** [comment]
I am confused by the same problem.
In my case, there are 2 thread running a infinite loop, but we can see some parts running out of the thread-loop.
![image](https://user-images.githubusercontent.com/10728431/178210227-500dd451-6fff-4b3d-b367-62e6835fe7e7.png)

Did you get the reason?
