### ISSUE TITLE
Coloring based on own time

### ISSUE THREAD

**Issue by aparamon** [brendangregg/FlameGraph#193]
Currently, it's possible to color nodes based of function name hash, or randomly.
I want to experiment with coloration based on node properties, namely node own time (node time minus child nodes time).
The relevant code is
https://github.com/brendangregg/FlameGraph/blob/f857ebc94bfe2a9bfdc4f1536ebacfb7466f69ba/flamegraph.pl#L1053-L1132
What's the best way to access node own time (node time minus child nodes time) there?

**Comment by aparamon** [comment]
Example flame graph for [perf-iperf-stacks-pidtid-01-collapsed-all.txt](https://github.com/brendangregg/FlameGraph/blob/master/test/results/perf-iperf-stacks-pidtid-01-collapsed-all.txt):
![flame](https://user-images.githubusercontent.com/2229284/50424453-118a8f80-0875-11e9-80a9-c1e8fc2e85a4.png)
Several outstanding time eaters are clearly visible.
Comments?

**Comment by DanielShaulov** [comment]
@aparamon - Why did you close the issue? Did you manage implement it?
