### ISSUE TITLE
"sudo perf script -i xxx.data > in-fb.perf" goes wrong 

### ISSUE THREAD

**Issue by Xunzhuo** [brendangregg/FlameGraph#253]
![image](https://user-images.githubusercontent.com/48784001/115004612-8e742400-9ed9-11eb-90e5-271b2210c6fd.png)

Failed to open /lib/x86_64-linux-gnu/libc-2.27.so, continuing without symbols
Failed to open /usr/local/bin/envoy, continuing without symbols
Failed to open /lib/x86_64-linux-gnu/libpthread-2.27.so, continuing without symbo
ls
Failed to open /tmp/perf-7223.map, continuing without symbols
Failed to open /lib/x86_64-linux-gnu/libm-2.27.so, continuing without symbols

**Comment by Kim1230** [comment]
Hello, have you found the solution?
