### ISSUE TITLE
本地安装了perl为什么提示不是有效的32位应用？

### ISSUE THREAD

**Issue by GavinXu520** [brendangregg/FlameGraph#269]
![f3e389a96b4b501560bed4149708c10](https://user-images.githubusercontent.com/13655605/142988503-ad30c64a-01ff-489e-ab81-1cf572e3f7be.png)

**Comment by GavinXu520** [comment]
flamegraph.pl写得有问题？只支持 32位应用？

**Comment by brendangregg** [comment]
This looks like a problem with how go-torch is launching flamegraph.pl on Windows.
