### ISSUE TITLE
Why does flamegraph.pl filters the data?

### ISSUE THREAD

**Issue by ibobak** [brendangregg/FlameGraph#61]
Dear Brendan,

I've attached here
https://drive.google.com/open?id=0B3DMXMfcPWF3ZTVpRGpDblFrVmc

the trace file of a size of 38MB which I've got after profiling Hadoop cluster using StatsD JVM Profiler (actually my fork of it).  

The file sortedx.txt in the attachment has a well formed structure:
stacktrace1  count
stacktrace2  count
...

etc.

No errors. Besides, I sorted stacktraces alphabetically.

But when I run ./flamegraph.pl  sortedx.txt > sortedx.svg,  I get the output of just 300KB is size.  Not as expected, of course. 

I see that there are stacktraces which have enormous count (contrary to the rest), so I later launched a command with awk  that filtered unnecessary strings and did this:

awk '!/EPollArrayWrapper|org.apache.hadoop.net.unix.DomainSocketWatcher|java.lang.UNIXProcess.waitForProcessExit|org.apache.hadoop.util.Shell$1.run:509;java.io.BufferedReader.readLine:382;java.io.BufferedReader.readLine:317;java.io.BufferedReader.fill:154;java.io.InputStreamReader.read:184;sun.nio.cs.StreamDecoder.read:177;sun.nio.cs.StreamDecoder.implRead:325;sun.nio.cs.StreamDecoder.readBytes:283;java.io.BufferedInputStream.read:334;java.io.BufferedInputStream.read1:273;java.io.FileInputStream.read:272;java.io.FileInputStream.readBytes/' sortedx.txt | ./flamegraph.pl >sortedx_after_filtering.svg 

AND....   sortedx_after_filtering.svg   is already  3MB in size! MUCH BETTER.

The question is next:  why do you filter some stacktraces?   Could you please, make an option in the 
flamegraph.pl  to REMOVE filtering of anything?

I am  asking because many processes in the cluster are running those "waiting" threads like "EPollWait" etc., but I don't care about them - I will simply drop down to where I need.   

Could you please make a fix?

Thanks

**Comment by brendangregg** [comment]
It doesn't filter. It will ignore invalid lines, and print that count as a warning. Sounds like your problem needs to be debugged!

**Comment by ibobak** [comment]
Brendan,  believe me, it does filter them.  In order to reproduce here you are - two files: 
https://drive.google.com/open?id=0B3DMXMfcPWF3T1ZSczdEM1U0N3c

the difference between sortedx.txt and sortedy.txt is in a dozen of lines:  I filtered sortedx.txt and got sortedy.txt.  Just run winmerge on these two files - and you will see that some lines are missing in sortedty.txt

So, if we run 
./flamegraph.pl  sortedy.txt >  sortedy.svg
it must produce A LITTLE BIT LESS  file than if we run
./flamegraph.pl  sortedx.txt >  sortedx.svg
right?

But in fact, I get   sortedy.svg about 10MB in size, while sortedx.svg is 300 kb.
It should NOT be like this.   

Note: I removed lines with these strings:

-----

EPollArrayWrapper

org.apache.hadoop.net.unix.DomainSocketWatcher

java.lang.UNIXProcess.waitForProcessExit

org.apache.hadoop.util.Shell$1.run:509;java.io.BufferedReader.readLine:382;java.io.BufferedReader.readLine:317;java.io.BufferedReader.fill:154;java.io.InputStreamReader.read:184;sun.nio.cs.StreamDecoder.read:177;sun.nio.cs.StreamDecoder.implRead:325;sun.nio.cs.StreamDecoder.readBytes:283;java.io.BufferedInputStream.read:334;java.io.BufferedInputStream.read1:273;java.io.FileInputStream.read:272;java.io.FileInputStream.readBytes

org.apache.hadoop.util.Shell$1.run:509;java.io.BufferedReader.readLine:382;java.io.BufferedReader.readLine:317;java.io.BufferedReader.fill:154;java.io.InputStreamReader.read:184;sun.nio.cs.StreamDecoder.read:177;sun.nio.cs.StreamDecoder.implRead:325;sun.nio.cs.StreamDecoder.readBytes:283;java.io.BufferedInputStream.read:334;java.io.BufferedInputStream.read1:273;java.io.FileInputStream.read:272;java.io.FileInputStream.readBytes.:2

java.lang.Thread.run:745;java.util.concurrent.ThreadPoolExecutor$Worker.run:615;java.util.concurrent.ThreadPoolExecutor.runWorker:1145;java.util.concurrent.FutureTask.run:262;org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call:81;org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call:299;org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer:197;org.apache.hadoop.util.Shell$ShellCommandExecutor.execute:702;org.apache.hadoop.util.Shell.run:455;org.apache.hadoop.util.Shell.runCommand:524;org.apache.hadoop.util.Shell$ShellCommandExecutor.parseExecResult:715;java.io.BufferedReader.read:279;java.io.BufferedReader.read1:205;java.io.BufferedReader.fill:154;java.io.InputStreamReader.read:184;sun.nio.cs.StreamDecoder.read:177;sun.nio.cs.StreamDecoder.implRead:325;sun.nio.cs.StreamDecoder.readBytes:283;java.io.BufferedInputStream.read:334;java.io.BufferedInputStream.read1:273;java.io.FileInputStream.read:272;java.io.FileInputStream.readBytes.:2

-----

These strings have too big quantity of calls (in comparison to the others). I think this is the reason.

**Comment by brendangregg** [comment]
It has minwidth for eliding data:

```
./flamegraph.pl --help
USAGE: ./flamegraph.pl [options] infile > outfile.svg

        --title       # change title text
        --width       # width of image (default 1200)
        --height      # height of each frame (default 16)
        --minwidth    # omit smaller functions (default 0.1 pixels)
```

**Comment by ibobak** [comment]
so, if I want everything to be included, I need to specify  --minwidth 0  and I will get everything.  
THANK YOU VERY MUCH!
